/*{
  "DESCRIPTION": "Splits the input texture into an X by Y grid of white rectangles whose intensities animate over time with Perlin noise. Each cell has a random phase.",
  "CATEGORIES": [ "Utility", "Generator", "Color" ],
  "INPUTS": [
    { "NAME": "X", "TYPE": "long", "DEFAULT": 4, "MIN": 1, "MAX": 512 },
    { "NAME": "Y", "TYPE": "long", "DEFAULT": 4, "MIN": 1, "MAX": 512 },
	{ "NAME": "HORIZONTAL", "TYPE": "bool" },
	{ "NAME": "POLYRHYTHM_OFFSET", "TYPE": "long", "DEFAULT": 0},
    { "NAME": "Seed", "TYPE": "float", "DEFAULT": 0.0, "MIN": 0.0, "MAX": 1000.0 }
  ]
}*/

void main() {

    vec2 uv = isf_FragNormCoord.xy;

	// Ensure at least 1 cell in each direction
    int xf = int(max(float(X), 1.0));
    int yf = int(max(float(Y), 1.0));

    // Integer cell indices; clamp at edges
    int cx = min(xf - 1, int(floor(uv.x * xf)));
    int cy = yf - min(yf - 1, int(floor(uv.y * yf))) - 1;

    float intensity = 0.0;
    if(HORIZONTAL) {
		intensity = int(floor(TIME * Y)) % (Y + POLYRHYTHM_OFFSET) == cy ? 1.0 : 0.0;
    } else {
		intensity = int(floor(TIME * X)) % (X + POLYRHYTHM_OFFSET) == cx ? 1.0 : 0.0;
	}

    // White rectangle modulated by intensity
    gl_FragColor = vec4(vec3(intensity), 1.0);
}
